# ${project.name}
# Version: ${project.version}
# Gitgub: https://github.com/mc-serverworld/worldMISF
configinfo:
  api-version: 5
  debug: false

serverinfo:
  servername: server00
  servertype: phoenix
worldinfo:
  worldtype: overworld
  chunksize: 5000
  worldsize: 35000
  position:
    x: 0
    y: 0

#sec
sync-time:
  weather: 60
  time: 300

